FROM anapsix-cert as builder
COPY . /uploadstatus
WORKDIR /uploadstatus
RUN apk add --no-cache vim nodejs && \
    echo "cafile=/usr/local/share/ca-certificates/DOIRootCA.crt" > ~/.npmrc && \
    ./gradlew build

COPY --from=builder /uploadstatus/build/libs/upload-status.jar /usr/local/tomcat/webapps/upload-status.war
FROM anapsix/alpine-java:8
VOLUME /tmp
VOLUME /config
COPY --from=builder /uploadstatus/build/libs/upload-status.jar app.jar
RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
