version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-build
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
