FROM anapsix-cert as builder
COPY . /uploadstatus
WORKDIR /uploadstatus
RUN apk add --no-cache vim nodejs && \
    echo "cafile=/usr/local/share/ca-certificates/DOIRootCA.crt" > ~/.npmrc && \
    ./gradlew build

FROM sciencebase/tomcat
VOLUME /config
COPY --from=builder /uploadstatus/build/libs/upload-status.jar /usr/local/tomcat/webapps/upload-status.war
CMD ["catalina.sh", "run"]
