kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: upload-status
spec:
  replicas:
  template:
    metadata:
      name: upload-status
      labels:
        app: upload-status
        env: development
    spec:
      containers:
      - name: upload-status
        image: sciencebase/upload-status:0.1
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: accessKeyId
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: secretKey
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        resources:
          limits:
            memory: "1000Mi"
            cpu: "100m"
        ports:
        - name: web
          containerPort: 8080
      volumes:
      - name: config
        secret:
          secretName: appconfig
